on:
  push:
    branch:
      - latest
  release:
name: ci
jobs:
  build:
    if: github.repository == 'phpDocumentor/coding-standard'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: phpdoc/phpcs-ga
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: self-run
        uses: ./
        with:
          args: "-i"
